In [1]:
import numpy as np

In [3]:
a = np.array([10,20,30,40,50,60,70])
print(a)
print(type(a))

[10 20 30 40 50 60 70]
<class 'numpy.ndarray'>


In [9]:
b = np.array([[1,2],[3,4]])
print("2D Array:")
print(b)

2D Array:
[[1 2]
 [3 4]]


In [22]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:")
print(c)

print("Shape:")
print(c.shape)



2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:
(3, 3)


In [24]:
print(c.ndim)

2


In [21]:
d = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print("3D Array:")
print(d)

print("Shape:")
print(d.shape)

3D Array:
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
Shape:
(3, 1, 3)


In [19]:
print(d.ndim)

3


In [26]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:")
print(c)

print("Shape:")
print(c.shape)

print(c.dtype)
print(c.size)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:
(3, 3)
int64
9


# SPECIAL ARRAYS

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# INDEXING AND SLICING 

In [34]:
a = np.array([59,26,28,36,18])
print(a[0])
print(a[3])
print(a[-1])

59
36
18


In [35]:
print(a[1:4])

[26 28 36]


In [42]:
a = np.array([[1,2,3],[5,6,7]])
print(a[1,1])
print(a[0])
print(a[:,1])


6
[1 2 3]
[2 6]


# DATATYPES AND CONVERSION

In [43]:
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [45]:
b = np.array([1.5, 2.5, 3.5])
print(b.dtype)

float64


In [46]:
a = np.array([1, 2, 3], dtype=float)
print(a)

[1. 2. 3.]


In [47]:
a = np.array([1.2, 2.8, 3.9])
b = a.astype(int)
print(b)

[1 2 3]


# MATHEMATICAL OPERATION

In [48]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[100 400 900]


# Aggregate & Statistical Functions

In [54]:
marks = np.array([70, 80, 90, 60, 100])
print(np.min(marks))
print(np.max(marks))
print(np.mean(marks))
print(np.sum(marks))
print(np.std(marks))
print(np.var(marks))

print(np.argmax(marks)) # returns the index

60
100
80.0
400
14.142135623730951
200.0
4


# LINEAR ALGEBRA

In [63]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [3,6],
    [9,2]
])

print(A+B)


print(A*B)



[[ 4  8]
 [12  6]]
[[ 3 12]
 [27  8]]


In [64]:
print(A@B) # MATRIX MULTIPLICATION

np.matmul(A, B)

[[21 10]
 [45 26]]


array([[21, 10],
       [45, 26]])

In [65]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

32

In [71]:
A.T #TRANSPOSE


array([[1, 3],
       [2, 4]])

In [72]:
print(A.transpose())

[[1 3]
 [2 4]]


# RESHAPING

In [77]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape


(6,)

In [78]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a.reshape(2, -1) #(-1)NumPy automatically calculates the missing dimension.

array([[1, 2, 3],
       [4, 5, 6]])

# STACKING

In [88]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))


array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# Conditional Operations

In [93]:
marks = np.array([35, 80, 45, 90, 20])
marks>50 #Boolean mask

array([False,  True, False,  True, False])

In [94]:
marks[marks>50]

array([80, 90])

In [95]:
np.where(marks>50,"Pass","Fail")

array(['Fail', 'Pass', 'Fail', 'Pass', 'Fail'], dtype='<U4')

# BROADCASTING

In [ ]:
#Broadcasting = NumPy automatically stretches dimensions of size 1 (or a scalar) so arrays can perform element-wise operations.
#Broadcasting means NumPy lets a smaller value/array participate in an operation with a bigger array by reusing its values wherever needed.

In [117]:
a = np.array([1, 2, 3])
b = 10

print(a + b)  #NumPy reuses 10 for every element. We don't have to manually create [10, 10, 10]

[11 12 13]


# RANDOM MODULE

In [118]:
np.random

<module 'numpy.random' from '/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/numpy/random/__init__.py'>

In [119]:
np.random.rand() #Gives a random number between:0 and 1

0.596850157946487

In [120]:
np.random.rand(5)

array([0.44583275, 0.09997492, 0.45924889, 0.33370861, 0.14286682])

In [121]:
np.random.randint(1,11)

3

In [122]:
np.random.randint(1,11,size=5)

array([6, 5, 2, 8, 6])

In [123]:
np.random.randint(1,100,5)

array([ 2, 64, 60, 21, 33])

# FUNCTIONS

In [124]:
a = np.array([30, 10, 50, 20])

np.sort(a)

array([10, 20, 30, 50])

In [126]:
a = np.array([1, 2, 2, 3, 3, 3])

np.unique(a)

array([1, 2, 3])

In [134]:
a = np.array([[2,3],[1, 2]])
b = np.array([[4,7],[3, 4]])

# axis=0 → add rows ↓
# axis=1 → add columns →

np.concatenate((a, b),axis=0)




array([[2, 3],
       [1, 2],
       [4, 7],
       [3, 4]])

In [135]:
np.concatenate((a, b),axis=1)

array([[2, 3, 4, 7],
       [1, 2, 3, 4]])

In [136]:
a = np.array([
    [1, 2],
    [3, 4]
])

a.ravel() #Converts multidimensional array into 1D.

array([1, 2, 3, 4])

In [137]:
a.flatten() #Converts multidimensional array into 1D.

array([1, 2, 3, 4])